#!/bin/sh

nvram_get() {
   r=`nvram get $1 | sed "s/$1=//"`
   if [ "$r" = "$1 do not exist!" ]; then
      return 0
   else
      echo "$r"
   fi
}

rc_log() {
   if [ -e /usr/etc/log_rc_flag ]; then
      echo "`date` [rc_dropbear] $@" >> /var/log/rc_calls
   fi
}

rc_log_echo() {
   rc_log "$@"
   echo "$@"
}

case "$1" in
   start)
      if [ "$(pidof dropbear)" ]; then
	 rc_log_echo "dropbear already running ($(pidof dropbear)).  Leaving it alone."
      else
	 # Check if we're missing the host key in /etc/dropbear
	 if [ ! -f /etc/dropbear/dropbear_ecdsa_host_key ]; then
	    mkdir -p /etc/dropbear
	    # Check if the host key is in NVRAM
	    if [ "$(nvram_get dropbear_ecdsa_host_key)" ]; then
	       # Populate /etc/dropbear/dropbear_ecdsa_host_key from NVRAM
	       nvram_get dropbear_ecdsa_host_key | uudecode 
	    else
	       # Generate a new key and save it both to /etc/dropbear/ and NVRAM
	       dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key -s 256
	       nvram set dropbear_ecdsa_host_key="`uuencode /etc/dropbear/dropbear_ecdsa_host_key /etc/dropbear/dropbear_ecdsa_host_key`"
	       nvram commit
	    fi
	 fi

	 # Set admin password from nvram
	 if [ "$(nvram_get http_password)" ]; then
	    echo root:$(nvram_get http_password) | chpasswd -m
	 fi

	 # Actually start the thing
	 if [ "$(nvram_get lan_ipaddr)" ]; then
	    /usr/sbin/dropbear -p $(nvram_get lan_ipaddr):22
	 fi

	 # Make sure it started
	 if [ "$(pidof dropbear)" ]; then
	    rc_log_echo "dropbear started ($(pidof dropbear)) successfully. (-p $(nvram_get lan_ipaddr):22)"
	 else
	    rc_log_echo "Error starting dropbear (-p $(nvram_get lan_ipaddr):22)"
	 fi
      fi
      ;;
   stop)
      if [ "$(pidof dropbear)" ]; then
	 /usr/sbin/kill -9 $(pidof dropbear)
	 rc_log_echo "dropbear stopped."
      else
	 rc_log_echo "dropbear is not running."
      fi
      ;;
   reload|restart)
      $0 stop
      $0 start
      ;;
   *)
      echo "Usage: $0 start|stop|restart|reload"
      exit 1
      ;;
esac

exit 0
